packages:
- '.'
# resolver: lts-6.20
# compiler: ghcjs-0.2.0.9006020_ghc-7.10.3
# compiler-check: match-exact
# setup-info:
#   ghcjs:
#     source:
#       ghcjs-0.2.0.9006020_ghc-7.10.3:
#          url: http://ghcjs.tolysz.org/lts-6.20-9006020.tar.gz
#          sha1: a6cea90cd8121eee3afb201183c6e9bd6bacd94a

resolver: lts-7.2
compiler: ghcjs-0.2.1.9007002_ghc-8.0.1
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9007002_ghc-8.0.1:
          url: http://ghcjs.tolysz.org/ghc-8.0-2016-10-01-lts-7.2-9007002.tar.gz
          sha1: a41ae415328e2b257d40724d13d1386390c26322
